
CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE STUDENTS (
  STUDENTS_ID INT PRIMARY KEY,
  STUDENTS_FIRST_NAME VARCHAR(50),
  STUDENTS_LAST_NAME VARCHAR(50),
  STUDENTS_EMAIL VARCHAR(100),
  STUDENTS_DEPARTMENT_ID INT,
  STUDENTS_JOINING_DATE DATE,
  FOREIGN KEY (STUDENTS_DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE SUBJECTS (
  SUBJECTS_ID INT AUTO_INCREMENT PRIMARY KEY,
  SUBJECTS_NAME VARCHAR(100),
  SUBJECTS_DEPARTMENT_ID INT,
  UNIQUE (SUBJECTS_NAME, SUBJECTS_DEPARTMENT_ID),
  time_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (SUBJECTS_DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE MARKS (
  MARKS_STUDENT_ID INT,
  MARKS_SUBJECT_ID INT,
  MARKS_SCORE INT CHECK (MARKS_SCORE BETWEEN 0 AND 100),
  PRIMARY KEY (MARKS_STUDENT_ID, MARKS_SUBJECT_ID),
  FOREIGN KEY (MARKS_STUDENT_ID) REFERENCES STUDENTS(STUDENTS_ID),
  FOREIGN KEY (MARKS_SUBJECT_ID) REFERENCES SUBJECTS(SUBJECTS_ID)
);

CREATE TABLE GRADE (
  GRADE_ID INT PRIMARY KEY,
  GRADE_CODE VARCHAR(10),
  GRADE_LABEL VARCHAR(50),
  PERCENTAGE_MIN INT,
  PERCENTAGE_MAX INT,
  GPA DECIMAL(3,1)
);


